name: hexlet-check
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Hexlet project check
        uses: hexlet/project-action@release
      - name: lint
        run: make lint
      - name: test
        run: make test
      env:
        CI: true
